# Generated by Django 5.0.6 on 2024-06-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_food_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='food',
            field=models.TextField(),
        ),
    ]
