# Generated by Django 5.0.6 on 2024-06-29 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_orderitem_order_remove_orderitem_food_orders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='food_quantity',
        ),
    ]
