# Generated by Django 5.0.6 on 2024-06-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_total_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
    ]
