# Generated by Django 5.0.6 on 2024-06-29 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_order_delete_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
